'use strict';
const path=require('path'); const Logger=require('./Logger'); const ConfigManager=require('./ConfigManager'); const StateManager=require('./StateManager'); const EventBus=require('./EventBus'); const JsonDatabase=require('./JsonDatabase'); const PermissionManager=require('./PermissionManager'); const GroupManager=require('./GroupManager'); const UserManager=require('./UserManager'); const ModerationManager=require('./ModerationManager'); const CommandRegistry=require('./CommandRegistry'); const EventLoader=require('./EventLoader'); const ConnectionManager=require('./ConnectionManager'); const HealthServer=require('./HealthServer'); const axios=require('axios'); const AiProvider=require('../ai/AiProvider');
class BotApp {
 constructor({rootDir=process.cwd()}={}) { this.rootDir=rootDir; this.logger=new Logger(); this.config=new ConfigManager({rootDir,logger:this.logger}); this.state=new StateManager(this.config.all(),this.logger); this.events=new EventBus(); this.db=new JsonDatabase({rootDir,logger:this.logger}); this.groups=new GroupManager(this.db); this.users=new UserManager(this.db); this.permissions=new PermissionManager(this.config,this.db); this.ai=new AiProvider({axios,config:this.config}); this.moderation=new ModerationManager({db:this.db,groups:this.groups,state:this.state}); this.connection=new ConnectionManager({config:this.config,state:this.state,events:this.events,logger:this.logger,rootDir}); const services={ai:this.ai,groups:this.groups,users:this.users,moderation:this.moderation}; this.commands=new CommandRegistry({commandsDir:path.join(rootDir,'src','cmds'),config:this.config,db:this.db,permissions:this.permissions,logger:this.logger,state:this.state,services}); this.eventLoader=new EventLoader({eventsDir:path.join(rootDir,'src','events'),bus:this.events,logger:this.logger,apiProvider:()=>this.connection.api,services:{...services,db:this.db,config:this.config}}); this.health=new HealthServer({app:this,logger:this.logger}); this.startedAt=Date.now(); this._shutdownBound=false; this._initialized=false; }
 async init(){if(this._initialized)return this;await this.db.init();this.commands.load();this.eventLoader.load();this.events.on('message',async({api,event})=>{if(event?.senderID)await this.users.recordMessage(event.senderID,event.senderName||'');if(event?.threadID)await this.groups.ensure(event.threadID);await this.commands.execute(api,event);});this.events.on('connection:error',e=>this.logger.error('Connection error:',e));this._bindShutdownSignals();this._initialized=true;return this;}
 async start(){await this.init();this.health.start();await this.connection.connect();return this;} async shutdown(signal='manual'){this.logger.info(`Shutting down (${signal})...`);await this.connection.disconnect();await this.health.stop();this.state.setState('status','offline');}
 status(){const status=this.state.getStatus();return {...status,botName:this.config.get('botName'),commands:this.commands.commands.size,users:this.db.data?.users?.length||0,groups:this.db.data?.groups?.length||0,connected:Boolean(this.connection.api),uptime:Date.now()-this.startedAt};}
 _bindShutdownSignals(){if(this._shutdownBound)return;this._shutdownBound=true;const shutdown=s=>this.shutdown(s).then(()=>process.exit(0)).catch(e=>{this.logger.error('Shutdown failed:',e);process.exit(1);});process.once('SIGINT',()=>shutdown('SIGINT'));process.once('SIGTERM',()=>shutdown('SIGTERM'));}
}
module.exports=BotApp;
